language: node_js

node_js:
  - "4.4"

sudo: false


before_script:
  # CC reporter
  - npm install -g codeclimate-test-reporter
  - npm install

cache:
  directories:
  - $HOME/.yarn-cache

script: sh ci.sh