language: node_js

node_js:
  - "4.4"

sudo: false


before_install:
  # Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

before_script:
  # CC reporter
  - npm install -g codeclimate-test-reporter

cache:
  directories:
  - $HOME/.yarn-cache

script: sh ci.sh